version: '1.0'
name: pipeline-20220714
displayName: 打包
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - pack
stages:
  - name: stage-98cacc8c
    displayName: 打包maven
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: '8'
        mavenVersion: 3.6.3
        commands:
          - mvn -B clean package -Dmaven.test.skip=true
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./ruoyi-admin/target/ruoyi-admin.jar
        settings: []
        caches:
          - ~/.m2
        notify: []
        strategy:
          retry: '0'
          expression: []
permissions:
  - role: admin
    members: []
